spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
# 如果字段为null，则不返回
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 210.43.37.254
    port: 6379
wechat :
  mpAppId: wxdfbca34ba5f5b419
  mpAppSecret: 8c15d94538b164084fcf520a917db38e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPaht: /var/weixin_cert/h5.p12
  notifyUrl: http://fzp45t.natappfree.cc/sell/pay/notify

github:
  ClientId: 087dbd2309e153c39d52
  ClinetSecret: b2020ef46d4f7a4956ab04024d2ce0ca07731f20
server:
  context-path: /sell

projectUrl:
  sell: http://localhost:8080